-- 1. إنشاء جدول جهات الاتصال
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  device_id text -- اختياري: لتمييز المصدر
);

-- 2. تفعيل نظام الحماية (Row Level Security)
alter table public.contacts enable row level security;

-- 3. سياسة السماح بالبحث للجميع (القراءة)
create policy "Enable read access for all users"
  on public.contacts for select
  using (true);

-- 4. سياسة السماح بالإضافة للجميع (المزامنة/الرفع)
create policy "Enable insert access for all users"
  on public.contacts for insert
  with check (true);

-- 5. إنشاء فهارس لتحسين سرعة البحث
create index if not exists idx_contacts_phone on public.contacts(phone);
create index if not exists idx_contacts_name on public.contacts(name);
